apiVersion: apps/v1
kind: Deployment
metadata:
  name: raycast-master
  labels:
    app: raycast-master
spec:
  replicas: 2
  selector:
    matchLabels:
      app: raycast-master
  template:
    metadata:
      labels:
        app: raycast-master
    spec:
      containers:
        - name: raycast-master
          image: 339712906342.dkr.ecr.us-west-2.amazonaws.com/raycast-master:latest
          ports:
            - containerPort: 50052
              name: grpc
          env:
            - name: WORKER_SERVICE_NAME
              value: "raycast-worker-service"
            - name: WORKER_NAMESPACE
              value: "default"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 50052
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 50052
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: raycast-master-service
  labels:
    app: raycast-master
spec:
  selector:
    app: raycast-master
  ports:
    - port: 50052
      targetPort: 50052
      name: grpc
  type: LoadBalancer
